version: 2.1
aliases:
  - &save_git_cache
    save_cache:
      paths:
        - .git
      key: v3-git-{{ .Revision }}
  - &restore_git_cache
    restore_cache:
      keys:
        - v3-git-{{ .Revision }}
        - v3-git-
  - &save_build_cache
    save_cache:
      paths:
        - build
      key: v3-build-{{ .Revision }}
  - &restore_build_cache
    restore_cache:
      keys:
        - v3-build-{{ .Revision }}
  - &save_dist_cache
    save_cache:
      paths:
        - dist
      key: v3-dist-{{ .Revision }}
  - &restore_dist_cache
    restore_cache:
      keys:
        - v3-dist-{{ .Revision }}
  - &save_npm_cache
    save_cache:
      paths:
        - node_modules
      key: v3-npm-{{ checksum "package-lock.json" }}-1
  - &restore_npm_cache
    restore_cache:
      keys:
        - v3-npm-{{ checksum "package-lock.json" }}-1
        - v3-npm-
  - &defaults
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo

jobs:
  setup:
    <<: *defaults
    steps:
      - *restore_git_cache
      - checkout
      - *restore_npm_cache
      - run: |
          rm -rf node_modules/scratch-vm
          npm install
          (cd node_modules/scratch-vm && npm install && $(npm bin)/webpack --colors --bail --silent)
      - *save_git_cache
      - *save_npm_cache
  lint:
    <<: *defaults
    steps:
      - *restore_git_cache
      - checkout
      - *restore_npm_cache
      - run:
          name: Lint
          command: npm run test:lint -- --quiet --output-file test-results/eslint/results.xml --format junit
      - store_test_results:
          path: test-results
  unit:
    <<: *defaults
    environment:
      JEST_JUNIT_OUTPUT_NAME: results.xml
    steps:
      - *restore_git_cache
      - checkout
      - *restore_npm_cache
      - run:
          name: Unit
          environment:
              JEST_JUNIT_OUTPUT_DIR: test-results/unit
          command: npm run test:unit -- --reporters="default" --reporters="jest-junit" --coverage --coverageReporters=text --coverageReporters=lcov --maxWorkers="2"
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: test-results
  build:
    <<: *defaults
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --max-old-space-size=4000
    steps:
      - *restore_git_cache
      - checkout
      - *restore_npm_cache
      - run:
          name: Build
          command: npm run build
      - *save_build_cache
      - *save_dist_cache
  store_build:
    <<: *defaults
    steps:
      - *restore_build_cache
      - store_artifacts:
          path: build
  store_dist:
    <<: *defaults
    steps:
      - *restore_dist_cache
      - store_artifacts:
          path: dist
  integration:
    <<: *defaults
    parallelism: 1
    environment:
      JEST_JUNIT_OUTPUT_NAME: results.txt
    steps:
      - *restore_git_cache
      - checkout
      - *restore_npm_cache
      - *restore_build_cache
      - run:
          name: Integration
          environment:
              JEST_JUNIT_OUTPUT_DIR: test-results/integration
          command: |
            export TESTFILES=$(circleci tests glob "test/integration/*.test.js" | circleci tests split --split-by=timings)
            $(npm bin)/jest ${TESTFILES} --reporters="default" --reporters="jest-junit" --runInBand
      - store_test_results:
          path: test-results

  deploy-gh-pages:
    <<: *defaults
    steps:
      - *restore_git_cache
      - checkout
      - *restore_npm_cache
      - *restore_build_cache
      - run: |
          git config --global user.email $(git log --pretty=format:"%ae" -n1)
          git config --global user.name $(git log --pretty=format:"%an" -n1)
      - run: npm run deploy -- -x -r https://${GH_TOKEN}@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git
      - run: npm run deploy:smalruby.app -- -x -r https://${GH_TOKEN}@github.com/$CIRCLE_PROJECT_USERNAME/smalruby.app.git

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - unit:
          requires:
            - setup
      - build:
          requires:
            - setup
      - integration:
          requires:
            - build
      - store_build:
          requires:
            - build
      - store_dist:
          requires:
            - build
      - deploy-gh-pages:
          requires:
            - lint
            - unit
            - integration
            - build
          filters:
            branches:
              only:
                - develop
